"""empty message

Revision ID: 4f481e3fc44f
Revises: 90bd920cce72
Create Date: 2023-11-26 13:07:13.452665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f481e3fc44f'
down_revision = '90bd920cce72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acompanhante', schema=None) as batch_op:
        batch_op.alter_column('idade',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acompanhante', schema=None) as batch_op:
        batch_op.alter_column('idade',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
