"""empty message

Revision ID: 6a6b84deeb8a
Revises: 272c63e29481
Create Date: 2023-11-18 21:57:58.013978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6b84deeb8a'
down_revision = '272c63e29481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casamento_assistente',
    sa.Column('casamento_id', sa.Integer(), nullable=False),
    sa.Column('assistente.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assistente.id'], ['assistente.id'], ),
    sa.ForeignKeyConstraint(['casamento_id'], ['casamento.id'], ),
    sa.PrimaryKeyConstraint('casamento_id', 'assistente.id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casamento_assistente')
    # ### end Alembic commands ###
