"""empty message

Revision ID: 756e80b2b88c
Revises: e6ee8ae85314
Create Date: 2023-11-26 13:48:21.651217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '756e80b2b88c'
down_revision = 'e6ee8ae85314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acompanhante', schema=None) as batch_op:
        batch_op.alter_column('idade',
               existing_type=mysql.ENUM('ZERO_CINCO_ANOS', 'SEIS_DEZ_ANOS', 'ADULTO'),
               type_=sa.String(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acompanhante', schema=None) as batch_op:
        batch_op.alter_column('idade',
               existing_type=sa.String(length=12),
               type_=mysql.ENUM('ZERO_CINCO_ANOS', 'SEIS_DEZ_ANOS', 'ADULTO'),
               existing_nullable=False)

    # ### end Alembic commands ###
