"""empty message

Revision ID: 90bd920cce72
Revises: 6fbc462ab312
Create Date: 2023-11-26 12:58:50.006901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90bd920cce72'
down_revision = '6fbc462ab312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acompanhante', schema=None) as batch_op:
        batch_op.alter_column('idade',
               existing_type=mysql.ENUM('ZERO_CINCO_ANOS', 'SEIS_DEZ_ANOS', 'ADULTO'),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acompanhante', schema=None) as batch_op:
        batch_op.alter_column('idade',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('ZERO_CINCO_ANOS', 'SEIS_DEZ_ANOS', 'ADULTO'),
               existing_nullable=False)

    # ### end Alembic commands ###
