"""empty message

Revision ID: d55b515fdfb5
Revises: 5d37f37cbd9e
Create Date: 2023-11-18 16:31:32.617082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55b515fdfb5'
down_revision = '5d37f37cbd9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convidado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casamento_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casamento', ['casamento_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convidado', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casamento_id')

    # ### end Alembic commands ###
